apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flask-volume-demo
spec:
  containers:
    - imagePullPolicy: Always
      image: python:3.6
      name: flask-vol-demo
      volumeMounts:
        - mountPath: /opt/app-root/src/static/
          name: kit
  restartPolicy: OnFailure
  volumes:
    - emptyDir: {}
      name: kit
      persistentVolumeClaim:
        claimName: vol-kitten #volume-name-here

