apiVersion: v1
kind: Pod
metadata:
  labels:
    app: course-flask-demo
spec:
  containers:
    - imagePullPolicy: Always
      image: python:3.6
      name: course-flask-demo
      volumeMounts:
        - mountPath: /opt/app-root/src/static/
          name: kit
  restartPolicy: OnFailure
  volumes:
    - emptyDir: {}
      name: kit
      PersistentVolumeClaim:
        claimName: #volume-name-here

